package exceptions.testthrows;

public class B {
	public static void f2(){
		C.f3();
	}
}
