package exceptions.testthrows;

public class B {
	public void f2(){
		
	}
}
