package exceptions.testthrows;

public class B {
	public static void f2(){
		try{
			C.f3();
		}catch(Exception e){
			throw e;
		}
	}
}
