package exceptions.testthrows;

public class A {
	public static void f1(){
		new B().f2();
	}
}
